ktor:
  application:
    modules:
      - com.bittokazi.ktor.auth.gateway.ApplicationKt.module
  deployment:
    port: 5035

proxy:
  enabled: true
  routes:
    "":
      - prefix: /
        target: http://127.0.0.1:8081
      - prefix: /app
        target: http://127.0.0.1:3039
      - prefix: /static
        target: http://127.0.0.1:3039
